name: 'Terraform Destroy'
#on:
#  push:
#    branches:
#      - dev

on: [workflow_dispatch]

jobs:
  deploy-to-azure:
    name: 'Destroy to Azure'
    env:

      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub Actions
        uses: actions/checkout@v3

# Terraform Init, Validate, Plan, and Destroy for Dev Environment
      - name: Terraform Dev Init
        id: tf_init_dev
        run: |
          terraform init \
            -reconfigure \
            -backend-config="storage_account_name=${{ secrets.DEV_STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ secrets.DEV_STORAGE_CONTAINER_NAME }}" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="access_key=${{ secrets.DEV_STORAGE_ACCESS_KEY }}"
        if: github.ref == 'refs/heads/dev'
        working-directory: '.'

      - name: Terraform Dev Validate
        id: tf_validate_dev
        run: |
          terraform validate -no-color
        if: github.ref == 'refs/heads/dev'
        working-directory: '.'

      - name: Terraform Dev Plan
        id: tf_plan_dev
        run: |
          export TF_VAR_client_id=${{ secrets.DEV_ARM_CLIENT_ID }}
          export TF_VAR_client_secret=${{ secrets.DEV_ARM_CLIENT_SECRET }}
          export TF_VAR_tenant_id=${{ secrets.DEV_ARM_TENANT_ID }}
          export TF_VAR_subscription_id=${{ secrets.DEV_ARM_SUBSCRIPTION_ID }}
          export TF_VAR_admin_login=${{ secrets.DEV_PSQL_ADMINISTRATOR_LOGIN_PASSWORD }}
          export TF_VAR_administrator_login_password=${{ secrets.DEV_PSQL_ADMIN_LOGIN }}
          terraform plan --var-file=terraform-dev.tfvars -no-color
        if: github.ref == 'refs/heads/dev'
        working-directory: '.'

      - name: Terraform Dev Destroy
        run: |
          export TF_VAR_client_id=${{ secrets.DEV_ARM_CLIENT_ID }}
          export TF_VAR_client_secret=${{ secrets.DEV_ARM_CLIENT_SECRET }}
          export TF_VAR_tenant_id=${{ secrets.DEV_ARM_TENANT_ID }}
          export TF_VAR_subscription_id=${{ secrets.DEV_ARM_SUBSCRIPTION_ID }}
          export TF_VAR_admin_login=${{ secrets.DEV_PSQL_ADMINISTRATOR_LOGIN_PASSWORD }}
          export TF_VAR_administrator_login_password=${{ secrets.DEV_PSQL_ADMIN_LOGIN }}
          terraform apply -destroy -auto-approve --var-file=terraform-dev.tfvars
        if: github.ref == 'refs/heads/dev'
        working-directory: '.'

# Terraform Init, Validate, Plan, and Destroy Stg Environment
      - name: Terraform Stg Init
        id: tf_init_stg
        run: |
          terraform init \
            -reconfigure \
            -backend-config="storage_account_name=${{ secrets.STG_STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ secrets.STG_STORAGE_CONTAINER_NAME }}" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="access_key=${{ secrets.STG_STORAGE_ACCESS_KEY }}"
        if: github.ref == 'refs/heads/stg'
        working-directory: '.'

      - name: Terraform Stg Validate
        id: tf_validate_stg
        run: |
          terraform validate -no-color
        if: github.ref == 'refs/heads/stg'
        working-directory: '.'

      - name: Terraform Stg Plan
        id: tf_plan_stg
        run: |
          export TF_VAR_client_id=${{ secrets.STG_ARM_CLIENT_ID }}
          export TF_VAR_client_secret=${{ secrets.STG_ARM_CLIENT_SECRET }}
          export TF_VAR_tenant_id=${{ secrets.STG_ARM_TENANT_ID }}
          export TF_VAR_subscription_id=${{ secrets.STG_ARM_SUBSCRIPTION_ID }}
          export TF_VAR_admin_login=${{ secrets.STG_PSQL_ADMINISTRATOR_LOGIN_PASSWORD }}
          export TF_VAR_administrator_login_password=${{ secrets.STG_PSQL_ADMIN_LOGIN }}
          terraform plan --var-file=terraform-stg.tfvars -no-color
        if: github.ref == 'refs/heads/stg'
        working-directory: '.'

      - name: Terraform Stg Destroy
        run: |
          export TF_VAR_client_id=${{ secrets.STG_ARM_CLIENT_ID }}
          export TF_VAR_client_secret=${{ secrets.STG_ARM_CLIENT_SECRET }}
          export TF_VAR_tenant_id=${{ secrets.STG_ARM_TENANT_ID }}
          export TF_VAR_subscription_id=${{ secrets.STG_ARM_SUBSCRIPTION_ID }}
          export TF_VAR_admin_login=${{ secrets.STG_PSQL_ADMINISTRATOR_LOGIN_PASSWORD }}
          export TF_VAR_administrator_login_password=${{ secrets.STG_PSQL_ADMIN_LOGIN }}
          terraform apply -destroy -auto-approve --var-file=terraform-stg.tfvars
        if: github.ref == 'refs/heads/stg'
        working-directory: '.'

# Terraform Init, Validate, Plan, and Destroy Prod Environment
      - name: Terraform Prod Init
        id: tf_init_prod
        run: |
          terraform init \
            -reconfigure \
            -backend-config="storage_account_name=${{ secrets.PROD_STORAGE_ACCOUNT_NAME }}" \
            -backend-config="container_name=${{ secrets.PROD_STORAGE_CONTAINER_NAME }}" \
            -backend-config="key=terraform.tfstate" \
            -backend-config="access_key=${{ secrets.PROD_STORAGE_ACCESS_KEY }}"
        if: github.ref == 'refs/heads/prod'
        working-directory: '.'

      - name: Terraform Prod Validate
        id: tf_validate_prod
        run: |
          terraform validate -no-color
        if: github.ref == 'refs/heads/prod'
        working-directory: '.'

      - name: Terraform Prod Plan
        id: tf_plan_prod
        run: |
          export TF_VAR_client_id=${{ secrets.PROD_ARM_CLIENT_ID }}
          export TF_VAR_client_secret=${{ secrets.PROD_ARM_CLIENT_SECRET }}
          export TF_VAR_tenant_id=${{ secrets.PROD_ARM_TENANT_ID }}
          export TF_VAR_subscription_id=${{ secrets.PROD_ARM_SUBSCRIPTION_ID }}
          export TF_VAR_admin_login=${{ secrets.PROD_PSQL_ADMINISTRATOR_LOGIN_PASSWORD }}
          export TF_VAR_administrator_login_password=${{ secrets.PROD_PSQL_ADMIN_LOGIN }}
          terraform plan --var-file=terraform-prod.tfvars -no-color
        if: github.ref == 'refs/heads/prod'
        working-directory: '.'

      - name: Terraform Prod Destroy
        run: |
          export TF_VAR_client_id=${{ secrets.PROD_ARM_CLIENT_ID }}
          export TF_VAR_client_secret=${{ secrets.PROD_ARM_CLIENT_SECRET }}
          export TF_VAR_tenant_id=${{ secrets.PROD_ARM_TENANT_ID }}
          export TF_VAR_subscription_id=${{ secrets.PROD_ARM_SUBSCRIPTION_ID }}
          export TF_VAR_admin_login=${{ secrets.PROD_PSQL_ADMINISTRATOR_LOGIN_PASSWORD }}
          export TF_VAR_administrator_login_password=${{ secrets.PROD_PSQL_ADMIN_LOGIN }}
          terraform apply -destroy -auto-approve --var-file=terraform-prod.tfvars
        if: github.ref == 'refs/heads/prod'
        working-directory: '.'